### ISSUE TITLE
SendGrid won’t allow me to create an account

### ISSUE THREAD

**Issue by JosieWei2023** [Tao-VanJS/twikoo-cloudflare#7]
Hi,

I want to try out the Sendgrid API  but it seems Sendgrid does not allow new users. How to solve this?

Can I change to a different mail API?

Thx

**Comment by Tao-VanJS** [comment]
The custom email integration is here:
https://github.com/twikoojs/twikoo-cloudflare/blob/f613ee42cc29b94d6a1b2c420f823a36845e46b0/src/index.js#L63

You can extend this part to allow more kinds of integrations.
